import { Arrival, Room, RoomType, RatePlan, BookingSource, ArrivalStatus } from './models/arrival.model';

const today = new Date();
today.setHours(0, 0, 0, 0);

export const ARRIVALS_MOCK_DATA: Arrival[] = [
  {
    id: 'RES-2024-1001',
    guestName: 'Amit Sharma',
    guestId: 'G-501',
    phone: '+91 9876543210',
    email: 'amit.s@example.com',
    roomNumber: null,
    roomType: 'Deluxe',
    ratePlan: 'Rack',
    source: 'Booking.com',
    eta: '14:30',
    checkIn: today,
    checkOut: new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000),
    nights: 3,
    adults: 2,
    children: 1,
    advancePaid: 5000,
    totalAmount: 18500,
    status: 'pending',
    isVip: false,
    specialRequests: 'High floor preferred',
    idVerified: false,
    nationality: 'Indian'
  },
  {
    id: 'RES-2024-1002',
    guestName: 'Sarah Jenkins',
    guestId: 'G-502',
    phone: '+1 415 555 0123',
    email: 'sarah.j@example.com',
    roomNumber: '204',
    roomType: 'Suite',
    ratePlan: 'Corporate',
    source: 'Direct',
    eta: '11:00',
    checkIn: today,
    checkOut: new Date(today.getTime() + 5 * 24 * 60 * 60 * 1000),
    nights: 5,
    adults: 1,
    children: 0,
    advancePaid: 15000,
    totalAmount: 45000,
    status: 'vip',
    isVip: true,
    specialRequests: 'Airport pickup arranged',
    idVerified: true,
    nationality: 'American'
  },
  {
    id: 'RES-2024-1003',
    guestName: 'Rajesh Kumar',
    guestId: 'G-503',
    phone: '+91 9988776655',
    email: 'rajesh.k@example.com',
    roomNumber: '105',
    roomType: 'Standard',
    ratePlan: 'Package',
    source: 'Walk-in',
    eta: '15:45',
    checkIn: today,
    checkOut: new Date(today.getTime() + 2 * 24 * 60 * 60 * 1000),
    nights: 2,
    adults: 2,
    children: 0,
    advancePaid: 0,
    totalAmount: 8000,
    status: 'checked-in',
    isVip: false,
    specialRequests: '',
    idVerified: true,
    nationality: 'Indian'
  },
  {
    id: 'RES-2024-1004',
    guestName: 'Vikram Singh',
    guestId: 'G-504',
    phone: '+91 9123456789',
    email: 'vikram.s@example.com',
    roomNumber: null,
    roomType: 'Deluxe',
    ratePlan: 'OTA',
    source: 'Agoda',
    eta: '18:00',
    checkIn: today,
    checkOut: new Date(today.getTime() + 1 * 24 * 60 * 60 * 1000),
    nights: 1,
    adults: 2,
    children: 2,
    advancePaid: 2000,
    totalAmount: 6500,
    status: 'no-show',
    isVip: false,
    specialRequests: 'Extra bed needed',
    idVerified: false,
    nationality: 'Indian'
  },
  // Add more to reach 24
  ...Array.from({ length: 20 }).map((_, i) => ({
    id: `RES-2024-100${i + 5}`,
    guestName: `Guest ${i + 5}`,
    guestId: `G-50${i + 5}`,
    phone: `+91 90000000${i + 5}`,
    email: `guest${i + 5}@example.com`,
    roomNumber: i % 3 === 0 ? `30${i}` : null,
    roomType: (['Standard', 'Deluxe', 'Junior Suite', 'Suite', 'Presidential'][i % 5]) as RoomType,
    ratePlan: (['Rack', 'Corporate', 'Package', 'OTA'][i % 4]) as RatePlan,
    source: (['Walk-in', 'Phone', 'Booking.com', 'Agoda', 'Corporate', 'Direct'][i % 6]) as BookingSource,
    eta: `${10 + (i % 10)}:00`,
    checkIn: today,
    checkOut: new Date(today.getTime() + (1 + (i % 4)) * 24 * 60 * 60 * 1000),
    nights: 1 + (i % 4),
    adults: 1 + (i % 2),
    children: i % 3,
    advancePaid: i % 2 === 0 ? 1000 : 0,
    totalAmount: 5000 + (i * 500),
    status: (['pending', 'confirmed', 'checked-in', 'pending', 'pending'][i % 5]) as ArrivalStatus,
    isVip: i % 8 === 0,
    specialRequests: i % 4 === 0 ? 'Quiet room' : '',
    idVerified: i % 2 === 0,
    nationality: 'Indian'
  }))
];

export const ROOMS_MOCK_DATA: Room[] = [
  { id: '1', number: '101', type: 'Standard', floor: 'Floor 1', view: 'City', status: 'Vacant Clean', features: ['Non-Smoking'] },
  { id: '2', number: '102', type: 'Standard', floor: 'Floor 1', view: 'City', status: 'Vacant Dirty', features: ['Non-Smoking'] },
  { id: '3', number: '201', type: 'Deluxe', floor: 'Floor 2', view: 'Garden', status: 'Vacant Clean', features: ['Non-Smoking', 'Balcony'] },
  { id: '4', number: '202', type: 'Deluxe', floor: 'Floor 2', view: 'Sea', status: 'Occupied', features: ['Smoking', 'Balcony'] },
  { id: '5', number: '203', type: 'Deluxe', floor: 'Floor 2', view: 'Sea', status: 'Vacant Clean', features: ['Non-Smoking', 'Balcony'] },
  { id: '6', number: '301', type: 'Suite', floor: 'Floor 3', view: 'Sea', status: 'OOO', features: ['Non-Smoking', 'Living Room'] },
  { id: '7', number: '302', type: 'Suite', floor: 'Floor 3', view: 'Sea', status: 'Vacant Clean', features: ['Non-Smoking', 'Living Room'] },
  ...Array.from({ length: 20 }).map((_, i) => ({
    id: `R-${i + 10}`,
    number: `${400 + i}`,
    type: (['Standard', 'Deluxe', 'Junior Suite', 'Suite', 'Presidential'][i % 5]) as RoomType,
    floor: `Floor ${Math.floor(i / 5) + 4}`,
    view: (['Sea', 'Garden', 'City'][i % 3]) as 'Sea' | 'Garden' | 'City',
    status: (['Vacant Clean', 'Vacant Dirty', 'Occupied', 'Vacant Clean'][i % 4]) as 'Vacant Clean' | 'Vacant Dirty' | 'Occupied' | 'OOO',
    features: ['Non-Smoking']
  }))
];
